#!/bin/sh
selfDir=$(cd "$(dirname "$0")"; pwd)

JIRA_HOST_104="https://jira.104.com.tw"
MAIN_FILE_DIR="$selfDir/.git_hook_jira"
GIT_IGNORE_DIR="$MAIN_FILE_DIR/.gitignore"
JIRA_USERNAME_DIR="$MAIN_FILE_DIR/.jira_username"
JIRA_HOST_DIR="$MAIN_FILE_DIR/.jira_host"
mkdir $MAIN_FILE_DIR
touch $GIT_IGNORE_DIR
printf "*" > $GIT_IGNORE_DIR

PRE_PUSH_DIR="./pre-push"
GIT_HOOK_DIR="./.git/hooks/"
GIT_HOOK_PRE_PUSH_DIR="./.git/hooks/pre-push"
cp -i $PRE_PUSH_DIR $GIT_HOOK_DIR
chmod +x $GIT_HOOK_PRE_PUSH_DIR

exec < /dev/tty
read -p "jira username: " JIRA_USERNAME
read -p "jira hostname: ($JIRA_HOST_104) " JIRA_HOST
if [[ "$JIRA_HOST" == "" ]]
then JIRA_HOST=$JIRA_HOST_104
fi
touch $JIRA_USERNAME_DIR
printf $JIRA_USERNAME > $JIRA_USERNAME_DIR
touch $JIRA_HOST_DIR
printf $JIRA_HOST > $JIRA_HOST_DIR